version: '3.8'

services:
  haproxy:
    image: haproxy:2.8-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./haproxy/combined.pem:/usr/local/etc/haproxy/combined.pem:ro
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - node-app-1
      - node-app-2
      - go-app-1
      - go-app-2

  node-app-1:
    build: ./node
    expose:
      - "3000"

  node-app-2:
    build: ./node
    expose:
      - "3000"

  go-app-1:
    build: ./go
    expose:
      - "8080"

  go-app-2:
    build: ./go
    expose:
      - "8080"